### ISSUE TITLE
Add commonjs build

### ISSUE THREAD

**Issue by nj314** [fabienjuif/use-bus#9]
Add commonjs build artifacts to this project's NPM distribution to combat issues with transpilation using babel. Attempting to run a project's jest unit tests results in unsuccessful transpilation. Error messages:
* `Jest encountered an unexpected token`
* `SyntaxError: Unexpected token {` on the first line of useBus/index.js

I've tried to exclude use-bus from transformIgnorePatterns in jest.config.js to no avail.
```
transformIgnorePatterns: ['\\\\node_modules\\\\(?!use-bus).+\\.js$'] // does not work
```

**Comment by fabienjuif** [comment]
Latest version should fix this.

Can you update use-bus to this version (which is 2.3.0) and tell me if this is ok for you @nj314 ?

**Comment by nj314** [comment]
Works perfectly! Thank you for the incredibly fast response 👍  This library has been a life-saver for dealing with excessive rendering due to Context value changes with functional components.

**Comment by fabienjuif** [comment]
Nice to hear 👍
